name: Prettier Check

on: [push]

jobs:
   prettier-check:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install
      - name: Check for Prettier errors
        run: npm run prettier-check
      - name: Check for TypeScript errors
        run: npm run type-check
