version: '3'
services:
  frontend:
    image: taronvardanyan/feezbak-web:latest
    ports:
      - "3000:3000" # Map your frontend container's port to the host's port

  backend:
    image: taronvardanyan/feezbak-api:latest
    ports:
      - "4000:4000" # Map your backend container's port to the host's port
    depends_on:
      - frontend # Ensure the frontend service starts before the backend

# Add any additional configurations or volumes as needed for your services