export enum FlexBoxEnum {
  CenterHorizontal = "display: flex; justify-content: center; align-items: center;",
  CenterVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column;",
  CenterBoth = "display: flex; justify-content: center; align-items: center; flex-direction: row; flex-wrap: wrap;",
  AlignStartVertical = "display: flex; justify-content: center; align-items: flex-start; flex-direction: column;",
  AlignEndVertical = "display: flex; justify-content: center; align-items: flex-end; flex-direction: column;",
  JustifyStartHorizontal = "display: flex; justify-content: flex-start; align-items: center; flex-direction: row;",
  JustifyEndHorizontal = "display: flex; justify-content: flex-end; align-items: center; flex-direction: row;",
  JustifyStartVertical = "display: flex; justify-content: center; align-items: flex-start; flex-direction: column;",
  StartCenterVertical = "display: flex; justify-content: flex-start; align-items: center; flex-direction:column;",
  EndCenterVertical = "display: flex; justify-content: flex-end; align-items: center; flex-direction: column;",
  EndEndHorizontal = "display: flex; justify-content: flex-end; align-items: flex-end; flex-direction: row;",
  ReverseVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column-reverse;",
  SpaceEvenlyHorizontal = "display: flex; justify-content: space-evenly; align-items: center; flex-direction: row;",
  SpaceEvenlyVertical = "display: flex; justify-content: center; align-items: space-evenly; flex-direction: column;",
  SpaceAroundHorizontal = "display: flex; justify-content: space-around; align-items: center; flex-direction: row;",
  SpaceBetweenStartVertical = "display: flex; justify-content: space-between; align-items: flex-start;",
  SpaceBetweenHorizontal = "display: flex; justify-content: space-between; align-items: center; flex-direction: row;",
  SpaceBetweenCenterVertical = "display: flex; justify-content: space-between; align-items: center; flex-direction: column;",
  StartStartVertical = "display: flex; justify-content: flex-start; align-items: flex-start; flex-direction: column;",
}
