export enum FlexBoxEnum {
  CenterHorizontal = "display: flex; justify-content: center; align-items: center; flex-direction: row",
  CenterVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column",
  CenterBoth = "display: flex; justify-content: center; align-items: center; flex-direction: row; flex-wrap: wrap",
  AlignStartHorizontal = "display: flex; justify-content: flex-start; align-items: center; flex-direction: row",
  AlignEndHorizontal = "display: flex; justify-content: flex-end; align-items: center; flex-direction: row",
  AlignStartVertical = "display: flex; justify-content: center; align-items: flex-start; flex-direction: column",
  AlignEndVertical = "display: flex; justify-content: center; align-items: flex-end; flex-direction: column",
  JustifyStartHorizontal = "display: flex; justify-content: flex-start; align-items: center; flex-direction: row",
  JustifyEndHorizontal = "display: flex; justify-content: flex-end; align-items: center; flex-direction: row",
  JustifyStartVertical = "display: flex; justify-content: center; align-items: flex-start; flex-direction: column",
  JustifyEndVertical = "display: flex; justify-content: center; align-items: flex-end; flex-direction: column",
  ReverseHorizontal = "display: flex; justify-content: center; align-items: center; flex-direction: row-reverse",
  ReverseVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column-reverse",
  SpaceEvenlyHorizontal = "display: flex; justify-content: space-evenly; align-items: center; flex-direction: row",
  SpaceEvenlyVertical = "display: flex; justify-content: center; align-items: space-evenly; flex-direction: column",
  SpaceAroundHorizontal = "display: flex; justify-content: space-around; align-items: center; flex-direction: row",
  SpaceAroundVertical = "display: flex; justify-content: center; align-items: space-around; flex-direction: column",
  SpaceBetweenHorizontal = "display: flex; justify-content: space-between; align-items: center; flex-direction: row",
  SpaceBetweenVertical = "display: flex; justify-content: center; align-items: space-between; flex-direction: column",
  WrapHorizontal = "display: flex; justify-content: center; align-items: center; flex-direction: row; flex-wrap: wrap",
  WrapVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column; flex-wrap: wrap",
}
