export enum FlexBoxEnum {
  CenterHorizontal = "display: flex; justify-content: center; align-items: center;",
  CenterVertical = "display: flex; justify-content: center; align-items: center; flex-direction: column;",
  AlignStartVertical = "display: flex; justify-contenst: center; align-items: flex-start; flex-direction: column;",
  JustifyStartHorizontal = "display: flex; justify-content: flex-start; align-items: center; flex-direction: row;",
  JustifyEndHorizontal = "display: flex; justify-content: flex-end; align-items: center; flex-direction: row;",
  JustifyStartVertical = "display: flex; justify-content: center; align-items: flex-start; flex-direction: column;",
  StartCenterVertical = "display: flex; justify-content: flex-start; align-items: center; flex-direction: column;",
  EndCenterVertical = "display: flex; justify-content: flex-end; align-items: center; flex-direction: column;",
  EndEndHorizontal = "display: flex; justify-content: flex-end; align-items: flex-end; flex-direction: row;",
  SpaceBetweenColumnStretch = "display: flex; justify-content: space-between; align-items: stretch; flex-direction: column;",
  SpaceBetweenStartVertical = "display: flex; justify-content: space-between; align-items: flex-start;",
  SpaceBetweenHorizontal = "display: flex; justify-content: space-between; align-items: center; flex-direction: row;",
  SpaceBetweenCenterVertical = "display: flex; justify-content: space-between; align-items: center; flex-direction: column;",
  StartStartVertical = "display: flex; justify-content: flex-start; align-items: flex-start; flex-direction: column;",
}
