name: Deploy to Digital Ocean

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.4.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Digital Ocean
      run: |
        ssh -i ssh_key user@${{ secrets.DROPLET_IP }}  'cd apps/feezbak-web && git pull origin master && yarn install && yarn build'

