name: Deploy to Surge

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Surge
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: yarn install

      - name: Build React App
        run: yarn build

      - name: Deploy to Surge
        run: npx surge --project ./build --domain feezbak.surge.sh
