name: Deploy Workflow

on:
  push:
    branches:
      - develop  # Replace with the branch you want to trigger this workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          ssh -i ssh_key root@$DROPLET_ID
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          DROPLET_ID: ${{ secrets.DROPLET_ID }}

      - name: Change directory
        run: cd apps/feezbak-web

      - name: Git Pull
        run: git pull origin master

      - name: Install Dependencies
        run: yarn

      - name: Build
        run: yarn build
