name: Deploy Staging

on:
  push:
    branches:
      - feature/update-dashboard-ui

jobs:
  test_jov:
    name: Test Job
    runs-on: Digital_Ocean
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3