name: Lighthouse Report Comment

on:
   pull_request:
      branches:
         - develop

jobs:
   lighthouse:
      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@v2

         - name: Lighthouse CI Action
           uses: foo-software/lighthouse-check-action@master
           with:
             urls: 'https://www.foo.software,https://www.google.com'
             format: json

         - name: Read Report File
           id: read-report
           run: echo "::set-output name=report::$(cat .lighthouseci/lighthouse/*.json)"

         - name: Create Comment
           uses: actions/github-script@v4
           with:
             github-token: ${{ secrets.GITHUB_TOKEN }}
             script: |
               const report = JSON.parse('${{ steps.read-report.outputs.report }}');
               const payload = {
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 issue_number: context.issue.number,
                 body: 'Lighthouse Report:\n\n```json\n' + JSON.stringify(report, null, 2) + '\n```'
               };
               await github.rest.issues.createComment(payload);
