name: Lighthouse Audit

on:
   pull_request:
      branches:
         - develop
      types:
         - opened
         - synchronize

jobs:
   lighthouse:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Install dependencies
           run: npm ci

         - name: Run Lighthouse
           run: npm run lighthouse -- --output=json

         - name: Comment on pull request
           uses: peter-evans/create-or-update-comment@v1
           with:
             issue-number: ${{ github.event.pull_request.number }}
             body: |
             Lighthouse Audit Results:
              ```json
               ${{ steps.lighthouse.outputs.stdout }}
              ```
