name: Prettier Check

on:
 push:
       branches:
          - develop

jobs:
  prettier-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Check for Prettier errors
        run: yarn run prettier-check
      - name: Check for TypeScript errors
        run: yarn run type-check
