name: Deploy to Vercel

on:
   push:
      branches:
         - master

jobs:
   build-and-deploy:
      runs-on: ubuntu-latest

      steps:
         - name: Checkout repository
           uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
           node-version: 14

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
           vercel-token: ${{ secrets.VERCEL_TOKEN }}
           vercel-org-id: FMcNE7a39oljK9Xk5831hJt3
           vercel-project-id: prj_xXjKu1KILrGi6fb5Qp7jXvvKFxV3 # Replace with your Vercel project ID
